on: [push]
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install npm modules
        run: npm install
      - name: run EsLint ğŸ•³
        run: npm run lint
      - name: run prettier check ğŸ–Œ
        run: npm run format:check
      - name: unit tests ğŸ§ª
        run: npm run test 